name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'npm dist-tag (e.g., latest, next, rc)'
        required: false
        default: 'next'

jobs:
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "yarn"
          registry-url: 'https://registry.npmjs.org'

      # Install dependencies
      - name: Install dependencies
        run: yarn install --frozen-lockfile

      # Build the project
      - name: Build project
        run: yarn build

      # Publish to npm
      - name: Publish to npm
        run: npm publish --provenance --tag ${{ github.event.inputs.tag }}


